# Generated by Django 5.1.7 on 2025-10-01 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='public_key',
            new_name='hedera_private_key_encrypted',
        ),
        migrations.AddField(
            model_name='user',
            name='hedera_public_key',
            field=models.TextField(blank=True, null=True),
        ),
    ]
